import assert from 'node:assert/strict';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

import {
  isForgeScopeInstallation,
  main,
  parseArgs,
  targetPaths,
  workspacePath
} from '../lib/cli.js';

async function tempContext() {
  const root = await mkdtemp(join(tmpdir(), 'forgescope-test-'));
  const cwd = join(root, 'project');
  const home = join(root, 'home');
  mkdirSync(cwd, { recursive: true });
  mkdirSync(home, { recursive: true });
  const logs = [];
  const errors = [];
  return {
    root,
    cwd,
    home,
    logs,
    errors,
    context: {
      cwd,
      home,
      log: (line) => logs.push(line),
      error: (line) => errors.push(line)
    }
  };
}

test('parseArgs defaults to project install for all clients', () => {
  assert.deepEqual(parseArgs([]), {
    command: 'install',
    client: 'all',
    global: false,
    force: false,
    dryRun: false,
    help: false,
    version: false
  });
});

test('parseArgs validates init scope', () => {
  assert.throws(() => parseArgs(['init', '--global']), /repository-local/);
  assert.equal(parseArgs(['install', '--client=codex', '--force']).client, 'codex');
});

test('project targets deduplicate Codex and Cursor shared path', async () => {
  const state = await tempContext();
  try {
    const targets = targetPaths('all', false, state.context);
    assert.equal(targets.length, 2);
    const shared = targets.find((target) => target.clients.includes('codex'));
    assert.deepEqual(shared.clients, ['codex', 'cursor']);
    assert.equal(shared.path, join(state.cwd, '.agents', 'skills', 'forgescope'));
  } finally {
    await rm(state.root, { recursive: true, force: true });
  }
});

test('install, status and uninstall manage only ForgeScope skill files', async () => {
  const state = await tempContext();
  try {
    assert.equal(main(['install', '--client', 'codex'], state.context), 0);
    const target = join(state.cwd, '.agents', 'skills', 'forgescope');
    assert.equal(isForgeScopeInstallation(target), true);

    state.logs.length = 0;
    assert.equal(main(['status', '--client', 'codex'], state.context), 0);
    assert.ok(state.logs.some((line) => line.startsWith('installed codex:')));

    assert.equal(main(['uninstall', '--client', 'codex'], state.context), 0);
    assert.equal(existsSync(target), false);
  } finally {
    await rm(state.root, { recursive: true, force: true });
  }
});

test('uninstall protects an unrecognized directory', async () => {
  const state = await tempContext();
  try {
    const target = join(state.cwd, '.agents', 'skills', 'forgescope');
    mkdirSync(target, { recursive: true });
    writeFileSync(join(target, 'SKILL.md'), '---\nname: something-else\n---\n', 'utf8');

    assert.equal(main(['uninstall', '--client', 'codex'], state.context), 0);
    assert.equal(existsSync(target), true);
    assert.ok(state.logs.some((line) => line.startsWith('protect  codex:')));
  } finally {
    await rm(state.root, { recursive: true, force: true });
  }
});

test('init creates workspace and preserves existing content by default', async () => {
  const state = await tempContext();
  try {
    const path = workspacePath(state.context);
    assert.equal(main(['init'], state.context), 0);
    assert.equal(existsSync(path), true);
    assert.match(readFileSync(path, 'utf8'), /^<!-- Generated by ForgeScope CLI/m);

    writeFileSync(path, '# custom review\n', 'utf8');
    assert.equal(main(['init'], state.context), 0);
    assert.equal(readFileSync(path, 'utf8'), '# custom review\n');

    assert.equal(main(['init', '--force'], state.context), 0);
    assert.match(readFileSync(path, 'utf8'), /# ForgeScope Review/);
  } finally {
    await rm(state.root, { recursive: true, force: true });
  }
});

test('uninstall preserves repository workspace', async () => {
  const state = await tempContext();
  try {
    assert.equal(main(['install', '--client', 'codex'], state.context), 0);
    assert.equal(main(['init'], state.context), 0);
    const path = workspacePath(state.context);
    assert.equal(main(['uninstall', '--client', 'codex'], state.context), 0);
    assert.equal(existsSync(path), true);
  } finally {
    await rm(state.root, { recursive: true, force: true });
  }
});
